services:
  - type: web
    name: sahar-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromSecret: MONGO_URI
      - key: JWT_SECRET
        fromSecret: JWT_SECRET
      - key: SENDGRID_API_KEY
        fromSecret: SENDGRID_API_KEY
      - key: SENDGRID_FROM_EMAIL
        fromSecret: SENDGRID_FROM_EMAIL
      - key: PORT
        value: 5000 